### ISSUE TITLE
Number indication for "bestrate.com.ua"

### ISSUE THREAD

**Issue by oleksii-suprun** [igor-shubin/MezhbankExchangeRate#2]
It will be nice if rates from "bestrate.com.ua" in addition to existing diagrams will be displayed in number format as was done for others sources.

**Comment by ihor-shubin** [comment]
You can do it yourself  and give me a pull request.

**Comment by oleksii-suprun** [comment]
Unfortunatelly, I don't have enough free time, but you can mark this issue as "change request" and keep it as a perspective feature
